version: 1.2
workflows:
  - subclass: wdl
    primaryDescriptorPath: /Dockstore.wdl
    testParameterFiles:
      - /dockstore.cwl.json
    authors:
      - name: Charles Overbeck
        email: charles@testing.org
